# Generated by Django 6.0.4 on 2026-04-20 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("facilities", "0001_initial"),
        ("geofence", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("gas_threshold", "가스 임계치 초과"),
                            ("power_overload", "전력 과부하"),
                            ("geofence_intrusion", "위험구역 진입"),
                            ("sensor_fault", "센서 오류"),
                        ],
                        max_length=30,
                        verbose_name="이벤트 유형",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("normal", "정상"),
                            ("warning", "주의"),
                            ("danger", "위험"),
                        ],
                        max_length=10,
                        verbose_name="위험도",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "발생"),
                            ("acknowledged", "확인"),
                            ("in_progress", "조치중"),
                            ("resolved", "완료"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "source_label",
                    models.CharField(
                        max_length=100, verbose_name="발생원 이름 캐시 (UI 표시용)"
                    ),
                ),
                (
                    "summary",
                    models.CharField(max_length=200, verbose_name="이벤트 요약"),
                ),
                ("first_detected_at", models.DateTimeField(verbose_name="최초 감지")),
                ("last_detected_at", models.DateTimeField(verbose_name="마지막 감지")),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events_acknowledged",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="facilities.facility",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_geofence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events_as_source",
                        to="geofence.geofence",
                    ),
                ),
                (
                    "source_power_device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events_as_source",
                        to="facilities.powerdevice",
                    ),
                ),
                (
                    "source_sensor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events_as_source",
                        to="facilities.gassensor",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events_as_worker",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "event",
            },
        ),
        migrations.CreateModel(
            name="AlarmRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alarm_type",
                    models.CharField(
                        choices=[
                            ("gas_threshold", "가스 임계치 초과"),
                            ("power_overload", "전력 과부하"),
                            ("geofence_intrusion", "위험구역 진입"),
                            ("sensor_fault", "센서 오류"),
                        ],
                        max_length=30,
                        verbose_name="알람 유형",
                    ),
                ),
                (
                    "gas_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("co", "CO (일산화탄소)"),
                            ("h2s", "H2S (황화수소)"),
                            ("co2", "CO2 (이산화탄소)"),
                            ("o2", "O2 (산소)"),
                            ("no2", "NO2 (이산화질소)"),
                            ("so2", "SO2 (이산화황)"),
                            ("o3", "O3 (오존)"),
                            ("nh3", "NH3 (암모니아)"),
                            ("voc", "VOC (휘발성유기화합물)"),
                            ("lel", "LEL (폭발하한계)"),
                        ],
                        default="",
                        max_length=10,
                        verbose_name="가스 종류 (GAS_THRESHOLD 시)",
                    ),
                ),
                (
                    "measured_value",
                    models.FloatField(blank=True, null=True, verbose_name="측정값"),
                ),
                (
                    "threshold_value",
                    models.FloatField(
                        blank=True, null=True, verbose_name="초과 임계치"
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("normal", "정상"),
                            ("warning", "주의"),
                            ("danger", "위험"),
                        ],
                        max_length=10,
                        verbose_name="위험도",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alarm_records",
                        to="facilities.facility",
                    ),
                ),
                (
                    "geofence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alarm_records",
                        to="geofence.geofence",
                    ),
                ),
                (
                    "power_device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alarm_records",
                        to="facilities.powerdevice",
                    ),
                ),
                (
                    "sensor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alarm_records",
                        to="facilities.gassensor",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alarm_records_as_worker",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alarms",
                        to="alerts.event",
                        verbose_name="묶인 이벤트",
                    ),
                ),
            ],
            options={
                "db_table": "alarm_record",
            },
        ),
        migrations.CreateModel(
            name="EventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "생성"),
                            ("confirmed", "확인"),
                            ("status_changed", "상태 변경"),
                            ("note_added", "메모 추가"),
                            ("resolved", "완료"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("active", "발생"),
                            ("acknowledged", "확인"),
                            ("in_progress", "조치중"),
                            ("resolved", "완료"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("active", "발생"),
                            ("acknowledged", "확인"),
                            ("in_progress", "조치중"),
                            ("resolved", "완료"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="alerts.event",
                    ),
                ),
            ],
            options={
                "db_table": "event_log",
            },
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["facility", "status", "risk_level"],
                name="idx_event_facility_status_risk",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["facility", "-created_at"], name="idx_event_facility_time"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                condition=models.Q(("source_sensor__isnull", False)),
                fields=["source_sensor", "status"],
                name="idx_event_source_sensor_status",
            ),
        ),
        migrations.AddIndex(
            model_name="alarmrecord",
            index=models.Index(
                fields=["event", "-created_at"], name="idx_alarm_event_time"
            ),
        ),
        migrations.AddIndex(
            model_name="alarmrecord",
            index=models.Index(
                fields=["sensor", "-created_at"], name="idx_alarm_sensor_time"
            ),
        ),
        migrations.AddIndex(
            model_name="alarmrecord",
            index=models.Index(
                fields=["facility", "alarm_type", "-created_at"],
                name="idx_alarm_facility_type_time",
            ),
        ),
        migrations.AddIndex(
            model_name="eventlog",
            index=models.Index(
                fields=["event", "created_at"], name="idx_event_log_event_time"
            ),
        ),
        migrations.AddIndex(
            model_name="eventlog",
            index=models.Index(
                fields=["actor", "-created_at"], name="idx_event_log_actor_time"
            ),
        ),
    ]
