# Generated by Django 6.0.4 on 2026-05-08 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0003_alter_alarmrecord_alarm_type_alter_event_event_type"),
        ("facilities", "0010_thresholdgroup_threshold"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HazardTypeGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="최근 수정일"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="그룹 코드"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="그룹 명")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최근 수정자",
                    ),
                ),
            ],
            options={
                "db_table": "hazard_type_group",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="HazardType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="최근 수정일"),
                ),
                (
                    "type_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="유형 코드"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="표시 명")),
                (
                    "display_color",
                    models.CharField(
                        default="orange", max_length=20, verbose_name="표시 색상 토큰"
                    ),
                ),
                (
                    "map_visible",
                    models.BooleanField(default=True, verbose_name="지도 표시 여부"),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최근 수정자",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="types",
                        to="alerts.hazardtypegroup",
                    ),
                ),
            ],
            options={
                "db_table": "hazard_type",
                "ordering": ["group__sort_order", "type_code"],
            },
        ),
        migrations.CreateModel(
            name="AlertPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="최근 수정일"),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("gas_threshold", "가스 경보"),
                            ("power_overload", "전력 이상"),
                            ("geofence_intrusion", "위험구역 진입"),
                            ("sensor_fault", "센서 이상"),
                            ("ppe_violation", "PPE 미착용"),
                            ("vr_training_not_done", "VR 교육 미이수"),
                            ("safety_check_pending", "작업 안전 체크리스트 미완료"),
                            ("inspection_scheduled", "점검 예정"),
                            ("batch_failed", "배치 실패"),
                            ("storage_overdue", "보관 주기 실패"),
                        ],
                        max_length=50,
                        verbose_name="대상 이벤트",
                    ),
                ),
                (
                    "policy_kind",
                    models.CharField(
                        choices=[
                            ("stateful", "상태 기반"),
                            ("immediate", "즉시"),
                            ("scheduled", "예정"),
                        ],
                        default="immediate",
                        max_length=20,
                    ),
                ),
                (
                    "target_user_types",
                    models.JSONField(
                        default=list,
                        help_text='lowercase user_type 배열, 예: ["facility_admin", "worker"]',
                    ),
                ),
                ("target_sensor_ids", models.JSONField(blank=True, default=list)),
                ("target_device_ids", models.JSONField(blank=True, default=list)),
                ("target_geofence_ids", models.JSONField(blank=True, default=list)),
                (
                    "channels",
                    models.JSONField(
                        default=list,
                        help_text='Notification.Channel.values 부분집합, 예: ["popup", "sms"]',
                    ),
                ),
                (
                    "condition_summary",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="목록 화면 캐시 — service 레이어에서 갱신 (Phase 4-e)",
                        max_length=300,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "target_facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL이면 전사 정책",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_policies",
                        to="facilities.facility",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최근 수정자",
                    ),
                ),
            ],
            options={
                "db_table": "alert_policy",
                "indexes": [
                    models.Index(
                        fields=["event_type", "is_active"],
                        name="idx_policy_event_active",
                    ),
                    models.Index(
                        fields=["target_facility", "is_active"],
                        name="idx_policy_fac_active",
                    ),
                ],
            },
        ),
    ]
