# Generated by Django 6.0.4 on 2026-05-08 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0005_seed_hazard_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="상세 본문"),
        ),
        migrations.AddField(
            model_name="event",
            name="policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="alerts.alertpolicy",
                verbose_name="트리거 정책",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="status_note",
            field=models.TextField(blank=True, default="", verbose_name="상태 메모"),
        ),
    ]
