# Generated by Django 6.0.4 on 2026-05-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0006_event_description_event_policy_event_status_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertpolicy",
            name="message_template",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Django Template 문법. 빈 값이면 Event.summary 사용",
                verbose_name="알림 메시지 템플릿",
            ),
        ),
    ]
