# Generated by Django 6.0.4 on 2026-05-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0009_seed_alert_policy_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alarmrecord",
            name="gas_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("co", "CO (일산화탄소)"),
                    ("h2s", "H2S (황화수소)"),
                    ("co2", "CO2 (이산화탄소)"),
                    ("o2", "O2 (산소)"),
                    ("no2", "NO2 (이산화질소)"),
                    ("so2", "SO2 (이산화황)"),
                    ("o3", "O3 (오존)"),
                    ("nh3", "NH3 (암모니아)"),
                    ("voc", "VOC (휘발성유기화합물)"),
                ],
                default="",
                max_length=10,
                verbose_name="가스 종류 (GAS_THRESHOLD 시)",
            ),
        ),
    ]
