# Generated by Django 6.0.4 on 2026-05-14 00:22

from django.db import migrations, models


def rename_anomaly_to_power_anomaly_ai(apps, schema_editor):
    """기존 alarm_type/event_type='anomaly' row 를 'power_anomaly_ai' 로 변경.

    PoC C4 + e2e 검증 시 만들어진 잔여 데이터 (AlarmRecord 7건, Event 4건).
    AlarmType.ANOMALY rename 으로 enum 정합성 회복.
    """
    AlarmRecord = apps.get_model("alerts", "AlarmRecord")
    Event = apps.get_model("alerts", "Event")
    AlarmRecord.objects.filter(alarm_type="anomaly").update(
        alarm_type="power_anomaly_ai"
    )
    Event.objects.filter(event_type="anomaly").update(event_type="power_anomaly_ai")


def rename_back(apps, schema_editor):
    AlarmRecord = apps.get_model("alerts", "AlarmRecord")
    Event = apps.get_model("alerts", "Event")
    AlarmRecord.objects.filter(alarm_type="power_anomaly_ai").update(
        alarm_type="anomaly"
    )
    Event.objects.filter(event_type="power_anomaly_ai").update(event_type="anomaly")


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0011_alter_alarmrecord_alarm_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmrecord',
            name='alarm_type',
            field=models.CharField(choices=[('gas_threshold', '가스 경보'), ('power_overload', '전력 이상'), ('geofence_intrusion', '위험구역 진입'), ('sensor_fault', '센서 이상'), ('ppe_violation', 'PPE 미착용'), ('vr_training_not_done', 'VR 교육 미이수'), ('safety_check_pending', '작업 안전 체크리스트 미완료'), ('inspection_scheduled', '점검 예정'), ('batch_failed', '배치 실패'), ('storage_overdue', '보관 주기 실패'), ('power_anomaly_ai', '전력 AI 이상 감지')], max_length=30, verbose_name='알람 유형'),
        ),
        migrations.AlterField(
            model_name='alertpolicy',
            name='event_type',
            field=models.CharField(choices=[('gas_threshold', '가스 경보'), ('power_overload', '전력 이상'), ('geofence_intrusion', '위험구역 진입'), ('sensor_fault', '센서 이상'), ('ppe_violation', 'PPE 미착용'), ('vr_training_not_done', 'VR 교육 미이수'), ('safety_check_pending', '작업 안전 체크리스트 미완료'), ('inspection_scheduled', '점검 예정'), ('batch_failed', '배치 실패'), ('storage_overdue', '보관 주기 실패'), ('power_anomaly_ai', '전력 AI 이상 감지')], max_length=50, verbose_name='대상 이벤트'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('gas_threshold', '가스 경보'), ('power_overload', '전력 이상'), ('geofence_intrusion', '위험구역 진입'), ('sensor_fault', '센서 이상'), ('ppe_violation', 'PPE 미착용'), ('vr_training_not_done', 'VR 교육 미이수'), ('safety_check_pending', '작업 안전 체크리스트 미완료'), ('inspection_scheduled', '점검 예정'), ('batch_failed', '배치 실패'), ('storage_overdue', '보관 주기 실패'), ('power_anomaly_ai', '전력 AI 이상 감지')], max_length=30, verbose_name='이벤트 유형'),
        ),
        migrations.RunPython(
            rename_anomaly_to_power_anomaly_ai,
            reverse_code=rename_back,
        ),
    ]
