# Generated by Django 6.0.4 on 2026-05-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0013_alarmrecord_ml_anomaly_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmrecord',
            name='alarm_type',
            field=models.CharField(choices=[('gas_threshold', '가스 경보'), ('power_overload', '전력 이상'), ('geofence_intrusion', '위험구역 진입'), ('sensor_fault', '센서 이상'), ('ppe_violation', 'PPE 미착용'), ('vr_training_not_done', 'VR 교육 미이수'), ('safety_check_pending', '작업 안전 체크리스트 미완료'), ('inspection_scheduled', '점검 예정'), ('batch_failed', '배치 실패'), ('storage_overdue', '보관 주기 실패'), ('power_anomaly_ai', '전력 AI 이상 감지'), ('gas_anomaly_ai', '가스 AI 이상 감지')], max_length=30, verbose_name='알람 유형'),
        ),
        migrations.AlterField(
            model_name='alertpolicy',
            name='event_type',
            field=models.CharField(choices=[('gas_threshold', '가스 경보'), ('power_overload', '전력 이상'), ('geofence_intrusion', '위험구역 진입'), ('sensor_fault', '센서 이상'), ('ppe_violation', 'PPE 미착용'), ('vr_training_not_done', 'VR 교육 미이수'), ('safety_check_pending', '작업 안전 체크리스트 미완료'), ('inspection_scheduled', '점검 예정'), ('batch_failed', '배치 실패'), ('storage_overdue', '보관 주기 실패'), ('power_anomaly_ai', '전력 AI 이상 감지'), ('gas_anomaly_ai', '가스 AI 이상 감지')], max_length=50, verbose_name='대상 이벤트'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('gas_threshold', '가스 경보'), ('power_overload', '전력 이상'), ('geofence_intrusion', '위험구역 진입'), ('sensor_fault', '센서 이상'), ('ppe_violation', 'PPE 미착용'), ('vr_training_not_done', 'VR 교육 미이수'), ('safety_check_pending', '작업 안전 체크리스트 미완료'), ('inspection_scheduled', '점검 예정'), ('batch_failed', '배치 실패'), ('storage_overdue', '보관 주기 실패'), ('power_anomaly_ai', '전력 AI 이상 감지'), ('gas_anomaly_ai', '가스 AI 이상 감지')], max_length=30, verbose_name='이벤트 유형'),
        ),
    ]
