# Generated by Django 6.0.4 on 2026-05-15 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0014_alter_alarmrecord_alarm_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최근 수정일')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='alerts.event', verbose_name='확인된 이벤트')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='최근 수정자')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_acknowledgements', to=settings.AUTH_USER_MODEL, verbose_name='확인한 사용자')),
            ],
            options={
                'db_table': 'event_acknowledgement',
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_eventack_user_time')],
                'constraints': [models.UniqueConstraint(fields=('event', 'user'), name='uq_event_user_ack')],
            },
        ),
    ]
