# Generated by Django 6.0.4 on 2026-05-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0015_eventacknowledgement'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmrecord',
            name='channel',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='PowerDevice 채널 (1~16)'),
        ),
    ]
