# Generated by Django 6.0.4 on 2026-05-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0016_alarmrecord_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmrecord',
            name='algorithm_source',
            field=models.CharField(blank=True, default='', help_text='power/gas anomaly_ai 알람만 채움. isolation_forest / arima / combined / night_abnormal. 룰 알람은 빈 문자열.', max_length=30, verbose_name='AI 알고리즘 출처'),
        ),
    ]
