# Generated by Django 6.0.4 on 2026-05-20 01:04
# T4 D3 — AlarmRecord.source 컬럼 추가 + 옛 데이터 backfill.

from django.db import migrations, models


def backfill_source(apps, schema_editor):
    """기존 행에 source 채우기.

    - alarm_type='power_anomaly_ai' / 'gas_anomaly_ai' → 'ai'
    - 그 외 (룰 알람) → 'static_legacy'

    분석 일관성 — T4 도입 전 데이터도 source 차원에서 필터 가능. 신규 알람에서는
    decide_alarm 매트릭스가 적절한 source 5종을 직접 결정.
    """
    AlarmRecord = apps.get_model("alerts", "AlarmRecord")
    AI_TYPES = ("power_anomaly_ai", "gas_anomaly_ai")
    AlarmRecord.objects.filter(alarm_type__in=AI_TYPES).update(source="ai")
    AlarmRecord.objects.exclude(alarm_type__in=AI_TYPES).update(source="static_legacy")


def reverse_backfill(apps, schema_editor):
    """rollback — source 컬럼 자체가 사라질 거라 별도 작업 불요."""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0018_alter_alarmrecord_algorithm_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="alarmrecord",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ai", "AI"),
                    ("static_cover_miss", "정적 보완 (AI 미탐 의심)"),
                    ("static_cover_inference_fail", "정적 보완 (AI 추론 실패)"),
                    ("static_cover_warmup", "정적 보완 (AI 워밍업)"),
                    ("static_no_ai_available", "정적 (AI 비활성 채널)"),
                    ("static_legacy", "정적 (T4 전 데이터)"),
                ],
                default="",
                help_text=(
                    "T4 도입 후 알람: ai / static_cover_miss / "
                    "static_cover_inference_fail / static_cover_warmup / "
                    "static_no_ai_available. T4 전 데이터는 static_legacy (backfill)."
                ),
                max_length=30,
                null=True,
                verbose_name="검출 주체 (AI vs 정적)",
            ),
        ),
        migrations.RunPython(backfill_source, reverse_backfill),
    ]
