# Generated by Django 6.0.4 on 2026-05-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0019_alarmrecord_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertpolicy',
            name='recommended_actions',
            field=models.JSONField(blank=True, default=dict, help_text='risk_level별 단계 리스트. 예: {"danger": [...], "warning": [...]} 또는 {"default": [...]}', verbose_name='권고 조치'),
        ),
    ]
