# Generated by Django 6.0.4 on 2026-05-26 05:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0022_seed_ai_anomaly_policies'),
        ('facilities', '0018_seed_power_facility_default'),
        ('geofence', '0003_geofence_updated_by_alter_geofence_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(condition=models.Q(('source_power_device__isnull', False)), fields=['source_power_device', 'status'], name='idx_event_source_power_status'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(condition=models.Q(('source_geofence__isnull', False)), fields=['source_geofence', 'status'], name='idx_event_src_geofence_status'),
        ),
    ]
