# Generated by Django 6.0.4 on 2026-06-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0023_add_event_source_power_geofence_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertpolicy',
            name='condition_summary',
            field=models.CharField(blank=True, default='', help_text='목록 화면 캐시 — service 레이어에서 갱신', max_length=300),
        ),
    ]
