# Generated by Django 6.0.4 on 2026-04-16 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geofence', '0001_initial'),
        ('sensors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_type', models.CharField(choices=[('gas_threshold', '가스 임계치 초과'), ('power_overload', '전력 과부하'), ('sensor_fault', '센서 오류')], max_length=100)),
                ('gas_type', models.CharField(blank=True, max_length=10, null=True)),
                ('measured_value', models.FloatField(blank=True, null=True)),
                ('threshold_value', models.FloatField(blank=True, null=True)),
                ('alarm_level', models.CharField(choices=[('warning', '주의'), ('danger', '위험')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', '활성'), ('acknowledged', '확인됨'), ('resolved', '해결됨')], default='active', max_length=30)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_records', to='sensors.facility')),
                ('geofence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarm_records', to='geofence.geofence')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alarms', to=settings.AUTH_USER_MODEL)),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarm_records', to='sensors.gassensor')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarm_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alarm_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_broadcast', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('severity', models.CharField(choices=[('normal', '정상'), ('warning', '주의'), ('danger', '위험')], default='normal', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='alarms.alarmrecord')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_check_items', to='sensors.facility')),
            ],
            options={
                'db_table': 'safety_check_item',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SafetyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_statuses', to='alarms.safetycheckitem')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'safety_status',
                'ordering': ['check_item__order'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('threshold_update', '임계치 수정'), ('geofence_create', '위험구역 생성'), ('geofence_update', '위험구역 수정'), ('geofence_delete', '위험구역 삭제'), ('alarm_resolve', '알람 해제'), ('sensor_register', '센서 등록'), ('user_create', '사용자 생성'), ('user_update', '사용자 수정')], max_length=50)),
                ('target_model', models.CharField(blank=True, max_length=100, null=True)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='alarmrecord',
            index=models.Index(fields=['is_active', 'alarm_level'], name='idx_alarm_record_active_level'),
        ),
        migrations.AddConstraint(
            model_name='safetycheckitem',
            constraint=models.UniqueConstraint(fields=('facility', 'order'), name='uq_safety_check_item_facility_order'),
        ),
        migrations.AddConstraint(
            model_name='safetystatus',
            constraint=models.UniqueConstraint(fields=('worker', 'check_item'), name='uq_safety_status_worker_item'),
        ),
    ]
