# Generated by Django 6.0.4 on 2026-05-08 09:30

import apps.notices.models.notice_attachment
import apps.notices.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("facilities", "0010_thresholdgroup_threshold"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="최근 수정일"),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "일반 공지"),
                            ("urgent", "긴급 공지"),
                            ("maintenance", "점검 안내"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="상단 고정"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notices_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL이면 전사 공지",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notices",
                        to="facilities.facility",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최근 수정자",
                    ),
                ),
            ],
            options={
                "db_table": "notice",
            },
        ),
        migrations.CreateModel(
            name="NoticeAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="최근 수정일"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.notices.models.notice_attachment.notice_attachment_path,
                        validators=[
                            apps.notices.validators.validate_max_10mb,
                            apps.notices.validators.validate_allowed_extension,
                        ],
                    ),
                ),
                (
                    "filename",
                    models.CharField(max_length=200, verbose_name="원본 파일명"),
                ),
                ("size", models.PositiveIntegerField(verbose_name="파일 크기(byte)")),
                (
                    "notice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="notices.notice",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최근 수정자",
                    ),
                ),
            ],
            options={
                "db_table": "notice_attachment",
            },
        ),
        migrations.AddIndex(
            model_name="notice",
            index=models.Index(
                fields=["-is_pinned", "-published_at"],
                name="idx_notice_pinned_published",
            ),
        ),
        migrations.AddIndex(
            model_name="notice",
            index=models.Index(
                fields=["category", "-published_at"], name="idx_notice_cat_published"
            ),
        ),
        migrations.AddIndex(
            model_name="noticeattachment",
            index=models.Index(
                fields=["notice"], name="notice_atta_notice__e968b2_idx"
            ),
        ),
    ]
