# Generated by Django 6.0.4 on 2026-05-12 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='삭제 일시'),
        ),
        migrations.AddField(
            model_name='notice',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices_deleted', to=settings.AUTH_USER_MODEL, verbose_name='삭제자'),
        ),
        migrations.AddField(
            model_name='notice',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='삭제 여부'),
        ),
    ]
