# Generated by Django 6.0.4 on 2026-04-21 04:45

import apps.geofence.models.geofence
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("facilities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoFence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="구역 이름")),
                (
                    "polygon",
                    models.JSONField(
                        validators=[apps.geofence.models.geofence.validate_polygon],
                        verbose_name="꼭짓점 좌표 배열",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("normal", "정상"),
                            ("warning", "주의"),
                            ("danger", "위험"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="위험도",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="설명"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="geo_fences",
                        to="facilities.facility",
                    ),
                ),
            ],
            options={
                "db_table": "geo_fence",
                "indexes": [
                    models.Index(
                        fields=["facility", "is_active"],
                        name="idx_geofence_facility_active",
                    ),
                    models.Index(
                        fields=["risk_level", "is_active"],
                        name="idx_geofence_risk_active",
                    ),
                ],
            },
        ),
    ]
