# Generated by Django 6.0.4 on 2026-04-16 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoFence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('zone_type', models.CharField(choices=[('danger', '위험구역'), ('warning', '주의구역'), ('normal', '안전구역')], max_length=100)),
                ('polygon', models.JSONField()),
                ('risk_level', models.IntegerField(choices=[(0, '정상'), (1, '주의'), (2, '위험')], default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_fences', to='sensors.facility')),
            ],
            options={
                'db_table': 'geo_fence',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkerPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('movement_status', models.CharField(choices=[('moving', '이동 중'), ('stationary', '정지'), ('idle', '대기')], default='moving', max_length=100)),
                ('measured_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('current_geofence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_positions', to='geofence.geofence')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'worker_position',
                'ordering': ['-measured_at'],
                'indexes': [models.Index(fields=['worker', '-measured_at'], name='idx_worker_position_worker_time')],
            },
        ),
    ]
