# Generated by Django 6.0.4 on 2026-04-16 03:11
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geofence", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="workerposition",
            new_name="idx_wpos_time",
            old_name="idx_worker_position_worker_time",
        ),
    ]
