# Generated by Django 6.0.4 on 2026-05-08 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataRetentionPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="최근 수정일"),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("gas_sensor", "유해가스 센서"),
                            ("power", "전력"),
                            ("position_node", "위치 노드"),
                        ],
                        max_length=20,
                        verbose_name="장비 유형",
                    ),
                ),
                (
                    "data_category",
                    models.CharField(
                        choices=[
                            ("gas_raw", "가스 원천 데이터"),
                            ("gas_anomaly", "가스 이상 이력"),
                            ("power_raw", "전력 원천 데이터"),
                            ("power_agg", "전력 집계 이력"),
                            ("position_hist", "위치 이력"),
                        ],
                        max_length=20,
                        verbose_name="데이터 분류",
                    ),
                ),
                (
                    "raw_retention_days",
                    models.PositiveIntegerField(
                        default=30, verbose_name="원천 보관 기간(일)"
                    ),
                ),
                (
                    "history_retention_days",
                    models.PositiveIntegerField(
                        default=180, verbose_name="이력 보관 기간(일)"
                    ),
                ),
                (
                    "delete_cycle",
                    models.CharField(
                        choices=[
                            ("daily", "매일"),
                            ("monthly_1", "매월 1일"),
                            ("monthly_15", "매월 15일"),
                            ("monthly_last", "매월 말일"),
                            ("quarterly", "분기 말"),
                        ],
                        default="daily",
                        max_length=20,
                        verbose_name="삭제 주기",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("memo", models.TextField(blank=True, default="")),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retention_policies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="담당자",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최근 수정자",
                    ),
                ),
            ],
            options={
                "db_table": "data_retention_policy",
                "ordering": ["device_type", "data_category"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("device_type", "data_category"),
                        name="uq_retention_device_category",
                    )
                ],
            },
        ),
    ]
