# Generated by Django 6.0.4 on 2026-05-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_category",
                    models.CharField(
                        choices=[
                            ("error", "오류"),
                            ("batch", "배치"),
                            ("service", "서비스"),
                        ],
                        max_length=20,
                        verbose_name="로그 분류",
                    ),
                ),
                (
                    "service_module",
                    models.CharField(
                        help_text='예: "celery.tasks.fire_alarm", "apps.alerts.services"',
                        max_length=100,
                        verbose_name="서비스 모듈",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        help_text="ERROR/WARNING/INFO",
                        max_length=10,
                        verbose_name="로그 레벨",
                    ),
                ),
                ("message", models.TextField()),
                ("extra", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "app_log",
                "indexes": [
                    models.Index(
                        fields=["log_category", "-created_at"],
                        name="idx_applog_cat_time",
                    ),
                    models.Index(fields=["-created_at"], name="idx_applog_time"),
                ],
            },
        ),
        migrations.CreateModel(
            name="IntegrationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "integration_type",
                    models.CharField(
                        choices=[
                            ("collect", "수집"),
                            ("transmit", "전송"),
                            ("sync", "동기화"),
                        ],
                        max_length=20,
                        verbose_name="연동 유형",
                    ),
                ),
                (
                    "target_system",
                    models.CharField(
                        help_text='형식: "FastAPI→DRF" 또는 "GasSensor:GS-001"',
                        max_length=100,
                        verbose_name="대상 시스템",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("success", "성공"),
                            ("failure", "실패"),
                            ("delay", "지연"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("extra", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "integration_log",
                "indexes": [
                    models.Index(
                        fields=["integration_type", "-created_at"],
                        name="idx_intlog_type_time",
                    ),
                    models.Index(
                        fields=["result", "-created_at"], name="idx_intlog_result_time"
                    ),
                    models.Index(fields=["-created_at"], name="idx_intlog_time"),
                ],
            },
        ),
    ]
