apiVersion: v1 #k8s의 어떤 api버전 기준으로 작성됐는지 선언
kind: Namespace # 무엇을 만드는 파일인가를 선언 "파일마다 kind가 바뀜"
metadata: # 이 파일의 namespace의 이름을 diconai로 지정
  name: diconai # 이후 모든 파일에 namespace:diconai가 붙어서 이 방
  #으로 묶임
