# Generated by Django 6.0.4 on 2026-04-21 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("user_create", "사용자 생성"),
                            ("user_deactivate", "사용자 비활성화"),
                            ("user_update", "사용자 정보 변경"),
                            ("permission_change", "권한 변경"),
                            ("device_create", "장비 등록"),
                            ("device_deactivate", "장비 비활성화"),
                            ("device_status_change", "장비 상태 변경"),
                            ("geofence_create", "구역 생성"),
                            ("geofence_update", "구역 수정"),
                            ("geofence_deactivate", "구역 비활성화"),
                            ("threshold_update", "임계치 변경"),
                            ("checklist_update", "체크리스트 변경"),
                            ("manual_event_action", "이벤트 수동 조치"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "target_model",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="대상 모델 이름",
                    ),
                ),
                (
                    "target_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="대상 레코드 ID",
                    ),
                ),
                ("old_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                ("description", models.TextField(blank=True, default="")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "system_log",
                "indexes": [
                    models.Index(
                        fields=["actor", "-created_at"], name="idx_syslog_actor_time"
                    ),
                    models.Index(
                        fields=["action_type", "-created_at"],
                        name="idx_syslog_action_time",
                    ),
                    models.Index(
                        fields=["target_model", "target_id", "-created_at"],
                        name="idx_syslog_target_time",
                    ),
                    models.Index(fields=["-created_at"], name="idx_syslog_time"),
                ],
            },
        ),
    ]
