# Generated by Django 6.0.4 on 2026-04-30 02:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("user_create", "사용자 생성"),
                    ("user_deactivate", "사용자 비활성화"),
                    ("user_update", "사용자 정보 변경"),
                    ("permission_change", "권한 변경"),
                    ("device_create", "장비 등록"),
                    ("device_deactivate", "장비 비활성화"),
                    ("device_status_change", "장비 상태 변경"),
                    ("geofence_create", "구역 생성"),
                    ("geofence_update", "구역 수정"),
                    ("geofence_deactivate", "구역 비활성화"),
                    ("threshold_update", "임계치 변경"),
                    ("checklist_update", "체크리스트 변경"),
                    ("manual_event_action", "이벤트 수동 조치"),
                    ("dept_create", "부서 생성"),
                    ("dept_update", "부서 수정"),
                    ("dept_delete", "부서 삭제"),
                    ("member_add", "구성원 추가"),
                    ("member_remove", "소속 제외"),
                    ("member_move", "부서 이동"),
                    ("leader_assign", "조직장 임명"),
                ],
                max_length=30,
            ),
        ),
    ]
