# Generated by Django 6.0.4 on 2026-04-20 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("facilities", "0001_initial"),
        ("geofence", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x", models.FloatField(verbose_name="x 좌표")),
                ("y", models.FloatField(verbose_name="y 좌표")),
                (
                    "movement_status",
                    models.CharField(
                        choices=[
                            ("moving", "이동 중"),
                            ("stationary", "정지"),
                            ("idle", "대기"),
                        ],
                        default="moving",
                        max_length=20,
                    ),
                ),
                ("measured_at", models.DateTimeField(db_index=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "current_geofence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="worker_positions",
                        to="geofence.geofence",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="worker_positions",
                        to="facilities.facility",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="positions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "worker_position",
                "indexes": [
                    models.Index(
                        fields=["worker", "-measured_at"], name="idx_wp_worker_time"
                    ),
                    models.Index(
                        fields=["facility", "-measured_at"], name="idx_wp_facility_time"
                    ),
                    models.Index(
                        fields=["current_geofence", "-measured_at"],
                        name="idx_wp_geofence_time",
                    ),
                ],
            },
        ),
    ]
