# Generated by Django 6.0.4 on 2026-05-08 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facilities", "0010_thresholdgroup_threshold"),
        ("positioning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workerposition",
            name="received_node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_positions",
                to="facilities.positionnode",
                verbose_name="수신 노드",
            ),
        ),
    ]
