# Generated by Django 6.0.4 on 2026-04-21 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="공장 이름")),
                ("address", models.CharField(max_length=500, verbose_name="공장 주소")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="운영 여부"),
                ),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_facilities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="담당 관리자",
                    ),
                ),
            ],
            options={
                "db_table": "facility",
            },
        ),
        migrations.CreateModel(
            name="GasSensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="하드웨어 식별자"
                    ),
                ),
                (
                    "device_name",
                    models.CharField(max_length=100, verbose_name="사용자 정의 이름"),
                ),
                ("x", models.FloatField(verbose_name="도면 x 좌표 (px)")),
                ("y", models.FloatField(verbose_name="도면 y 좌표 (px)")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("normal", "정상"),
                            ("error", "오류"),
                            ("offline", "오프라인"),
                            ("inactive", "비활성"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("status_updated_at", models.DateTimeField(blank=True, null=True)),
                ("last_reading", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="facilities.facility",
                    ),
                ),
            ],
            options={
                "db_table": "gas_sensor",
            },
        ),
        migrations.CreateModel(
            name="PowerDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="하드웨어 식별자"
                    ),
                ),
                (
                    "device_name",
                    models.CharField(max_length=100, verbose_name="사용자 정의 이름"),
                ),
                ("x", models.FloatField(verbose_name="도면 x 좌표 (px)")),
                ("y", models.FloatField(verbose_name="도면 y 좌표 (px)")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("normal", "정상"),
                            ("error", "오류"),
                            ("offline", "오프라인"),
                            ("inactive", "비활성"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("status_updated_at", models.DateTimeField(blank=True, null=True)),
                ("last_reading", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel_count",
                    models.PositiveSmallIntegerField(
                        default=16, verbose_name="채널 수"
                    ),
                ),
                (
                    "channel_meta",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='예: {"1": {"name": "메인 에어컨", "scale": 1.5, "offset": 0}, "2": {"name": "조명", "scale": 1.0, "offset": -0.5}}',
                        verbose_name="채널 메타데이터",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="facilities.facility",
                    ),
                ),
            ],
            options={
                "db_table": "power_device",
            },
        ),
        migrations.AddIndex(
            model_name="facility",
            index=models.Index(fields=["is_active"], name="idx_facility_active"),
        ),
        migrations.AddIndex(
            model_name="gassensor",
            index=models.Index(
                fields=["facility", "is_active"], name="idx_gas_sensor_facility_active"
            ),
        ),
        migrations.AddIndex(
            model_name="gassensor",
            index=models.Index(
                fields=["status", "is_active"], name="idx_gas_sensor_status"
            ),
        ),
        migrations.AddIndex(
            model_name="powerdevice",
            index=models.Index(
                fields=["facility", "is_active"], name="idx_pwrdev_facility_active"
            ),
        ),
        migrations.AddIndex(
            model_name="powerdevice",
            index=models.Index(
                fields=["status", "is_active"], name="idx_power_device_status"
            ),
        ),
    ]
