# Generated by Django 6.0.4 on 2026-04-29 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facilities", "0003_facility_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="positionnode",
            name="facility",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="facilities.facility",
            ),
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="설비명")),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="비고"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="사용 여부"),
                ),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipments",
                        to="facilities.facility",
                        verbose_name="소속 공장",
                    ),
                ),
                (
                    "power_device",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipment",
                        to="facilities.powerdevice",
                        verbose_name="연결 전력 장치",
                    ),
                ),
            ],
            options={
                "db_table": "equipment",
                "indexes": [
                    models.Index(
                        fields=["facility", "is_active"],
                        name="idx_equipment_facility_active",
                    )
                ],
            },
        ),
    ]
