# Generated by Django 6.0.4 on 2026-04-30 02:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_gas_sensor_fields_inspection"),
        ("facilities", "0004_equipment_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gassensor",
            name="connection_checked_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="마지막 연결 확인일시"
            ),
        ),
        migrations.AddField(
            model_name="gassensor",
            name="connection_ok",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="연결 확인 결과"
            ),
        ),
        migrations.AddField(
            model_name="gassensor",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gas_sensors",
                to="accounts.department",
                verbose_name="관리 부서",
            ),
        ),
        migrations.AddField(
            model_name="gassensor",
            name="device_code",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="장비 코드"
            ),
        ),
        migrations.AddField(
            model_name="gassensor",
            name="ip_address",
            field=models.CharField(
                blank=True, default="", max_length=45, verbose_name="통신 IP"
            ),
        ),
        migrations.AddField(
            model_name="gassensor",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_gas_sensors",
                to=settings.AUTH_USER_MODEL,
                verbose_name="관리 담당자",
            ),
        ),
        migrations.AddField(
            model_name="gassensor",
            name="notes",
            field=models.TextField(blank=True, default="", verbose_name="비고"),
        ),
        migrations.AddField(
            model_name="gassensor",
            name="port",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="통신 PORT"
            ),
        ),
        migrations.CreateModel(
            name="GasSensorInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[("regular", "정기 점검"), ("abnormal", "이상 점검")],
                        max_length=20,
                        verbose_name="점검 구분",
                    ),
                ),
                (
                    "inspection_date",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="점검일"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("action_needed", "조치 필요"), ("normal", "정상")],
                        max_length=20,
                        verbose_name="점검 상태",
                    ),
                ),
                ("notes", models.TextField(verbose_name="점검 의견")),
                (
                    "expected_action_date",
                    models.DateField(blank=True, null=True, verbose_name="예상 조치일"),
                ),
                (
                    "is_actioned",
                    models.BooleanField(default=False, verbose_name="조치 완료"),
                ),
                (
                    "action_date",
                    models.DateField(blank=True, null=True, verbose_name="조치 완료일"),
                ),
                (
                    "action_notes",
                    models.TextField(blank=True, default="", verbose_name="조치 의견"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gas_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="조치 담당자",
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gas_inspections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="점검자",
                    ),
                ),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="facilities.gassensor",
                        verbose_name="대상 센서",
                    ),
                ),
            ],
            options={
                "db_table": "gas_sensor_inspection",
                "ordering": ["-inspection_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["sensor", "inspection_date"],
                        name="idx_insp_sensor_date",
                    )
                ],
            },
        ),
    ]
