# Generated by Django 6.0.4 on 2026-05-07 00:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facilities", "0007_power_device_admin_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="powerdeviceinspection",
            options={
                "ordering": ["-inspection_date", "-created_at"],
                "verbose_name": "전력 장치 점검",
            },
        ),
        migrations.AlterField(
            model_name="powerdevice",
            name="channel_meta",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="채널 메타데이터"
            ),
        ),
        migrations.AlterField(
            model_name="powerdeviceinspection",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
