# Generated by Django 6.0.4 on 2026-05-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facilities", "0011_seed_threshold_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="threshold",
            name="chart_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="프론트 차트 스케일링용. 운영자가 어드민에서 조정",
                max_digits=12,
                null=True,
                verbose_name="차트 Y축 최대값",
            ),
        ),
    ]
