# Generated by Django 6.0.4 on 2026-05-08 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facilities", "0013_backfill_chart_max"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="최근 수정자",
            ),
        ),
        migrations.AddField(
            model_name="gassensor",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="최근 수정자",
            ),
        ),
        migrations.AddField(
            model_name="gassensorinspection",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="최근 수정자",
            ),
        ),
        migrations.AddField(
            model_name="positionnode",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="최근 수정자",
            ),
        ),
        migrations.AddField(
            model_name="powerdevice",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="최근 수정자",
            ),
        ),
        migrations.AddField(
            model_name="powerdeviceinspection",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="최근 수정자",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
        ),
        migrations.AlterField(
            model_name="facility",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="최근 수정일"),
        ),
        migrations.AlterField(
            model_name="gassensor",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
        ),
        migrations.AlterField(
            model_name="gassensor",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="최근 수정일"),
        ),
        migrations.AlterField(
            model_name="gassensorinspection",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
        ),
        migrations.AlterField(
            model_name="gassensorinspection",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="최근 수정일"),
        ),
        migrations.AlterField(
            model_name="positionnode",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
        ),
        migrations.AlterField(
            model_name="positionnode",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="최근 수정일"),
        ),
        migrations.AlterField(
            model_name="powerdevice",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
        ),
        migrations.AlterField(
            model_name="powerdevice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="최근 수정일"),
        ),
        migrations.AlterField(
            model_name="powerdeviceinspection",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
        ),
        migrations.AlterField(
            model_name="powerdeviceinspection",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="최근 수정일"),
        ),
    ]
