# Generated by Django 6.0.4 on 2026-05-08 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facilities", "0014_facility_updated_by_gassensor_updated_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="threshold",
            options={"ordering": ["group", "measurement_item", "facility"]},
        ),
        migrations.RemoveConstraint(
            model_name="threshold",
            name="uq_threshold_group_item",
        ),
        migrations.AddField(
            model_name="threshold",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                help_text="None=전사 정책. specific facility는 해당 공장에만 적용",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thresholds",
                to="facilities.facility",
                verbose_name="대상 공장",
            ),
        ),
        migrations.AddConstraint(
            model_name="threshold",
            constraint=models.UniqueConstraint(
                fields=("group", "measurement_item", "facility"),
                name="uq_threshold_group_item_facility",
            ),
        ),
    ]
