# Generated by Django 6.0.4 on 2026-05-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0018_seed_power_facility_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='threshold',
            name='condition_type',
            field=models.CharField(choices=[('gt', '초과'), ('gte', '이상'), ('lt', '미만'), ('lte', '이하')], default='gt', max_length=5, verbose_name='판단조건'),
        ),
        migrations.AddField(
            model_name='thresholdgroup',
            name='apply_scope',
            field=models.JSONField(blank=True, default=list, help_text='예: ["realtime", "ai", "alert"]', verbose_name='반영 범위'),
        ),
    ]
