# Generated by Django 6.0.4 on 2026-04-16 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_facilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'facility',
            },
        ),
        migrations.CreateModel(
            name='GasSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('device_name', models.CharField(max_length=20)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('status', models.CharField(choices=[('normal', '정상'), ('error', '오류'), ('offline', '오프라인')], default='normal', max_length=30)),
                ('last_reading', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas_sensors', to='sensors.facility')),
            ],
            options={
                'db_table': 'gas_sensor',
            },
        ),
        migrations.CreateModel(
            name='PowerDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('device_name', models.CharField(max_length=50)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('channel_count', models.IntegerField(default=16)),
                ('status', models.CharField(choices=[('normal', '정상'), ('error', '오류'), ('offline', '오프라인')], default='normal', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_devices', to='sensors.facility')),
            ],
            options={
                'db_table': 'power_device',
            },
        ),
        migrations.CreateModel(
            name='PowerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('power_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_events', to='sensors.powerdevice')),
            ],
            options={
                'db_table': 'power_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GasData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co', models.FloatField(blank=True, null=True)),
                ('h2s', models.FloatField(blank=True, null=True)),
                ('co2', models.FloatField(blank=True, null=True)),
                ('o2', models.FloatField(blank=True, null=True)),
                ('no2', models.FloatField(blank=True, null=True)),
                ('so2', models.FloatField(blank=True, null=True)),
                ('o3', models.FloatField(blank=True, null=True)),
                ('nh3', models.FloatField(blank=True, null=True)),
                ('voc', models.FloatField(blank=True, null=True)),
                ('lel', models.FloatField(blank=True, null=True)),
                ('risk_level', models.IntegerField(choices=[(0, '정상'), (1, '주의'), (2, '위험')], default=0)),
                ('error_field', models.CharField(blank=True, max_length=50, null=True)),
                ('measured_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('gas_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas_data', to='sensors.gassensor')),
            ],
            options={
                'db_table': 'gas_data',
                'ordering': ['-measured_at'],
                'indexes': [models.Index(fields=['gas_sensor', '-measured_at'], name='idx_gas_data_sensor_time')],
            },
        ),
        migrations.CreateModel(
            name='PowerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.IntegerField()),
                ('data_type', models.CharField(choices=[('current', '전류 (A)'), ('voltage', '전압 (V)'), ('watt', '전력 (W)')], max_length=30)),
                ('value', models.FloatField()),
                ('risk_level', models.IntegerField(blank=True, choices=[(0, '정상'), (1, '주의'), (2, '위험')], null=True)),
                ('measured_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('power_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_data', to='sensors.powerdevice')),
            ],
            options={
                'db_table': 'power_data',
                'ordering': ['-measured_at'],
                'indexes': [models.Index(fields=['power_device', 'channel', '-measured_at'], name='idx_power_data_device_channel_time')],
                'constraints': [models.UniqueConstraint(fields=('power_device', 'channel', 'measured_at'), name='uq_power_data_device_channel_time')],
            },
        ),
    ]
