# Generated by Django 6.0.4 on 2026-04-16 03:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sensors", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="powerdata",
            new_name="idx_pwr_ch_time",
            old_name="idx_power_data_device_channel_time",
        ),
    ]
