# Generated by Django 6.0.4 on 2026-04-20 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("alerts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_broadcast",
                    models.BooleanField(
                        default=False, verbose_name="브로드캐스트 여부 (공장 전체)"
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("normal", "정상"),
                            ("warning", "주의"),
                            ("danger", "위험"),
                        ],
                        max_length=10,
                        verbose_name="심각도",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("popup", "브라우저 팝업"),
                            ("push", "모바일 푸시"),
                            ("sms", "SMS"),
                            ("email", "이메일"),
                        ],
                        default="popup",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("pending", "발송 대기"),
                            ("sent", "발송됨"),
                            ("delivered", "수신 확인"),
                            ("failed", "발송 실패"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "delivery_error",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="발송 실패 사유",
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="alerts.event",
                        verbose_name="원천 이벤트",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="수신자 (개인 알림)",
                    ),
                ),
            ],
            options={
                "db_table": "notification",
                "indexes": [
                    models.Index(
                        fields=["target_user", "is_read", "-created_at"],
                        name="idx_notif_user_unread",
                    ),
                    models.Index(
                        fields=["event", "-created_at"], name="idx_notif_event_time"
                    ),
                    models.Index(
                        fields=["delivery_status", "-created_at"],
                        name="idx_notif_status_time",
                    ),
                    models.Index(
                        condition=models.Q(("is_broadcast", True)),
                        fields=["is_broadcast", "-created_at"],
                        name="idx_notif_broadcast_time",
                    ),
                ],
            },
        ),
    ]
