# Generated by Django 6.0.4 on 2026-05-08 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0006_event_description_event_policy_event_status_note"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="last_attempted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="최근 발송 시도 시각"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="alerts.alertpolicy",
                verbose_name="트리거 정책",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="retry_count",
            field=models.PositiveIntegerField(default=0, verbose_name="재시도 횟수"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="alerts.event",
                verbose_name="원천 이벤트",
            ),
        ),
    ]
