"""
Django settings for config project.

Generated by "django-admin startproject" using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import environ
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG", default=False)

ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=["127.0.0.1", "localhost"])


# Application definition

INSTALLED_APPS = [
    # DRF
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # apps
    "apps.accounts",
    "apps.facilities",
    "apps.geofence",
    "apps.positioning",
    "apps.monitoring",
    "apps.alerts",
    "apps.notifications",
    "apps.safety",
    "apps.core",
    "apps.dashboard",
    "apps.operations",
    "apps.reference",
    "apps.notices",
    "apps.training",
    "apps.ml",
]

MIDDLEWARE = [
    "apps.core.prometheus.PrometheusMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # 템플릿 폴더 설정
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "apps.core.context_processors.frontend_config",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASE_URL이 없으면 로컬 개발용 sqlite로 폴백.
# 운영: postgres://user:pass@host:5432/dbname 형식
DATABASES = {
    "default": env.db(
        "DATABASE_URL",
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

AUTH_USER_MODEL = "accounts.CustomUser"

# ── Django REST Framework ──────────────────────────────────
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    # 응답 봉투 표준 {error: {code, message, details?}}로 4xx/5xx 변환.
    "EXCEPTION_HANDLER": "apps.core.exceptions.standard_exception_handler",
    # OpenAPI 자동 스키마 (drf-spectacular)
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# ── drf-spectacular (OpenAPI / Swagger) ────────────────────
SPECTACULAR_SETTINGS = {
    "TITLE": "diconai API",
    "DESCRIPTION": "산재 예방 통합 관제 시스템 — drf-server REST API",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    # 어드민·내부 ingest 등 도메인별로 그룹핑
    "SCHEMA_PATH_PREFIX": r"/api/",
    "COMPONENT_SPLIT_REQUEST": True,
}

# ── Simple JWT ────────────────────────────────────────────
# Phase 5: blacklist 도입 + access lifetime 단축 + refresh 회전
# - access 1h: XSS 노출 시간 95% 감소 (24h → 1h). env로 운영별 조정 가능.
# - ROTATE_REFRESH_TOKENS: refresh 사용 시 새 refresh 발급 (1회용)
# - BLACKLIST_AFTER_ROTATION: 회전된 refresh는 blacklist 등록 → 재사용 차단
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        hours=env.int("JWT_ACCESS_TOKEN_LIFETIME_HOURS", default=1)
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=env.int("JWT_REFRESH_TOKEN_LIFETIME_DAYS", default=30)
    ),
    "AUTH_HEADER_TYPES": ("Bearer",),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    # Phase 5 WS 인증: fastapi가 같은 키로 검증할 수 있도록 명시.
    # 기본값 SECRET_KEY는 SimpleJWT 기본 동작과 동일 (호환 유지).
    "SIGNING_KEY": env("JWT_SIGNING_KEY", default=SECRET_KEY),
}

# ── 백오피스 URL (관리자 메뉴 이동) ───────────────────────
ADMIN_BACKOFFICE_URL = env(
    "ADMIN_BACKOFFICE_URL", default="/admin-panel/accounts-management/"
)

# Phase 3-e: Notification "지연" 동적 판정 임계값.
# delivery_status=PENDING + (now - last_attempted_at > N분) 이면 화면에 "지연" 라벨.
# enum 5종으로 비대화 안 함 — 동적 판정만.
NOTIFICATION_DELAY_THRESHOLD_MINUTES = env.int(
    "NOTIFICATION_DELAY_THRESHOLD_MINUTES", default=5
)

# ── FastAPI 서버 (서버 간 호출용, localhost) ──────────────
# Celery → FastAPI WS 브리지(/internal/alarms/push/) 호출에 사용.
# 브라우저는 별도로 FRONTEND_WS_BASE_URL을 통해 직접 fastapi와 WS 연결.
FASTAPI_INTERNAL_URL = env("FASTAPI_INTERNAL_URL", default="http://127.0.0.1:8001")

# ── 서비스 간 인증 토큰 (Phase 5) ──────────────────────────
# fastapi → drf 인입 엔드포인트, drf Celery → fastapi /internal/alarms/push/ 양방향에 사용.
# 빈 문자열이면 인증 비활성 (기존 동작 유지). 운영에서는 양 서비스에 동일 값 설정.
INTERNAL_SERVICE_TOKEN = env("INTERNAL_SERVICE_TOKEN", default="")

# ── 프론트엔드 노출용 URL (config.js로 주입) ───────────────
# 브라우저가 fastapi-server에 접속할 때 사용하는 공개 주소.
# 운영 환경에서는 도메인/HTTPS로 교체.
FRONTEND_API_BASE_URL = env(
    "FRONTEND_API_BASE_URL", default=""
)  # 빈 문자열이면 same-origin (Django 호스트)
FRONTEND_WS_BASE_URL = env("FRONTEND_WS_BASE_URL", default="ws://127.0.0.1:8001")

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# ML 모델 (.pkl) 저장 경로 — MEDIA_ROOT 밖, 웹 서버가 서빙하지 못하도록.
# Docker 환경: drf-server 와 fastapi-server 가 같은 named volume 마운트 (다음 sprint).
ML_MODELS_DIR = env("ML_MODELS_DIR", default=str(BASE_DIR / "ml_models"))


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# 개발(DEBUG=True): WhiteNoise가 STATICFILES_DIRS에서 직접 서빙 + 매 요청마다 파일 재스캔.
# collectstatic 호출이나 gunicorn 재시작 없이도 CSS/JS/HTML 변경이 즉시 반영된다.
# 운영(DEBUG=False): 해시 매니페스트 + gzip 압축으로 캐시 버스팅·CDN 친화 유지.
if DEBUG:
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    WHITENOISE_USE_FINDERS = True
    WHITENOISE_AUTOREFRESH = True
else:
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

LANGUAGE_CODE = "ko-kr"
TIME_ZONE = "Asia/Seoul"
USE_TZ = True

# ── Logging ──────────────────────────────────────────────────
# 컨벤션 (docs/dev_convention.md §6):
#   - 모듈별 logger: logger = logging.getLogger(__name__)
#   - 메시지 포맷: f"[CATEGORY] key=value key=value"
#   - 레벨: DEBUG(상세) / INFO(정상완료) / WARNING(주의·재시도) / ERROR(실패)
LOG_LEVEL = env("DJANGO_LOG_LEVEL", default="INFO")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "diconai": {
            "format": "{asctime} {levelname:<7} {name}: {message}",
            "datefmt": "%Y-%m-%d %H:%M:%S",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "diconai",
        },
        # AppLog 영속화 — Phase 2-d.
        # ERROR 이상만 캡처 (level=ERROR). 동기 INSTALL — 부하 측정 후 Phase 4에서 비동기 검토.
        # 재귀 가드는 핸들러 내부 thread-local 플래그로 처리.
        "applog_db": {
            "class": "apps.operations.logging.db_handler.DBLogHandler",
            "level": "ERROR",
            "formatter": "diconai",
        },
    },
    "root": {
        "handlers": ["console", "applog_db"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        "django.request": {  # 4xx/5xx 응답 시 Django가 traceback을 남김
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}

# ── Redis ─────────────────────────────────────────────────────
# 로컬 개발: Redis 설치 후 기본 포트(6379)로 실행하면 별도 설정 없이 동작.
# Windows: https://github.com/microsoftarchive/redis/releases
# Mac:     brew install redis && brew services start redis
# Linux:   sudo apt install redis-server && sudo service redis start
# .env에 REDIS_URL=redis://localhost:6379/0 추가 필요.
REDIS_URL = env("REDIS_URL", default="redis://localhost:6379/0")

# ── Celery ────────────────────────────────────────────────────
# Celery worker 실행: celery -A config worker -l info
# (DRF 서버와 별도 터미널에서 실행해야 함)
CELERY_BROKER_URL = REDIS_URL  # 태스크 전달 채널 (Redis)
CELERY_RESULT_BACKEND = REDIS_URL  # 태스크 결과 저장 (Redis)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True

# Phase 4-g: DataRetentionPolicy 보관 배치 — 매일 새벽 3시 실행
# is_cycle_due()가 정책별 delete_cycle 판정 (DAILY/MONTHLY_*/QUARTERLY)
# Celery beat 실행: celery -A config beat -l info
from celery.schedules import crontab  # noqa: E402

CELERY_BEAT_SCHEDULE = {
    "data_retention_daily": {
        "task": "apps.operations.tasks.data_retention_task.run_data_retention",
        "schedule": crontab(hour=3, minute=0),
        "args": (False,),  # dry_run=False (실제 삭제)
    },
    # Celery 큐 길이를 30초마다 읽어 Prometheus Gauge에 기록한다.
    # 큐 길이 추이를 보고 worker 증설 또는 전용 큐 분리 시점을 결정.
    # timedelta 사용: crontab은 최소 1분 단위라 30초 주기는 timedelta로 설정.
    "celery_queue_length_metrics": {
        "task": "apps.operations.tasks.queue_metrics_task.record_celery_queue_length",
        "schedule": timedelta(seconds=30),
    },
}

# ── Cache (Redis) ─────────────────────────────────────────────
# 가스 알람 상태(normal/warning/danger)와 WARNING 타이머 task ID를 저장.
# Redis가 동일하게 사용되므로 추가 인프라 없이 동작.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_URL,
    }
}
