"""
Django settings for config project.

Generated by "django-admin startproject" using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import environ
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG", default=False)

ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=["127.0.0.1", "localhost"])


# Application definition

INSTALLED_APPS = [
    # DRF
    "rest_framework",
    "drf_spectacular",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # apps
    "apps.accounts",
    "apps.facilities",
    "apps.geofence",
    "apps.positioning",
    "apps.monitoring",
    "apps.alerts",
    "apps.notifications",
    "apps.safety",
    "apps.core",
    "apps.dashboard",
    "apps.operations",
    "apps.reference",
    "apps.notices",
    "apps.training",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # 템플릿 폴더 설정
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "apps.core.context_processors.frontend_config",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASE_URL이 없으면 로컬 개발용 sqlite로 폴백.
# 운영: postgres://user:pass@host:5432/dbname 형식
DATABASES = {
    "default": env.db(
        "DATABASE_URL",
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

AUTH_USER_MODEL = "accounts.CustomUser"

# ── Django REST Framework ──────────────────────────────────
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    # 응답 봉투 표준 {error: {code, message, details?}}로 4xx/5xx 변환.
    "EXCEPTION_HANDLER": "apps.core.exceptions.standard_exception_handler",
    # OpenAPI 자동 스키마 (drf-spectacular)
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# ── drf-spectacular (OpenAPI / Swagger) ────────────────────
SPECTACULAR_SETTINGS = {
    "TITLE": "diconai API",
    "DESCRIPTION": "산재 예방 통합 관제 시스템 — drf-server REST API",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    # 어드민·내부 ingest 등 도메인별로 그룹핑
    "SCHEMA_PATH_PREFIX": r"/api/",
    "COMPONENT_SPLIT_REQUEST": True,
}

# ── Simple JWT ────────────────────────────────────────────
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        hours=env.int("JWT_ACCESS_TOKEN_LIFETIME_HOURS", default=24)
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=env.int("JWT_REFRESH_TOKEN_LIFETIME_DAYS", default=30)
    ),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# ── 백오피스 URL (관리자 메뉴 이동) ───────────────────────
ADMIN_BACKOFFICE_URL = env(
    "ADMIN_BACKOFFICE_URL", default="/admin-panel/accounts-management/"
)

# Phase 3-e: Notification "지연" 동적 판정 임계값.
# delivery_status=PENDING + (now - last_attempted_at > N분) 이면 화면에 "지연" 라벨.
# enum 5종으로 비대화 안 함 — 동적 판정만.
NOTIFICATION_DELAY_THRESHOLD_MINUTES = env.int(
    "NOTIFICATION_DELAY_THRESHOLD_MINUTES", default=5
)

# ── FastAPI 서버 (서버 간 호출용, localhost) ──────────────
# Celery → FastAPI WS 브리지(/internal/alarms/push/) 호출에 사용.
# 브라우저는 별도로 FRONTEND_WS_BASE_URL을 통해 직접 fastapi와 WS 연결.
FASTAPI_INTERNAL_URL = env("FASTAPI_INTERNAL_URL", default="http://127.0.0.1:8001")

# ── 프론트엔드 노출용 URL (config.js로 주입) ───────────────
# 브라우저가 fastapi-server에 접속할 때 사용하는 공개 주소.
# 운영 환경에서는 도메인/HTTPS로 교체.
FRONTEND_API_BASE_URL = env(
    "FRONTEND_API_BASE_URL", default=""
)  # 빈 문자열이면 same-origin (Django 호스트)
FRONTEND_WS_BASE_URL = env("FRONTEND_WS_BASE_URL", default="ws://127.0.0.1:8001")

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

LANGUAGE_CODE = "ko-kr"
TIME_ZONE = "Asia/Seoul"
USE_TZ = True

# ── Logging ──────────────────────────────────────────────────
# 컨벤션 (docs/dev_convention.md §6):
#   - 모듈별 logger: logger = logging.getLogger(__name__)
#   - 메시지 포맷: f"[CATEGORY] key=value key=value"
#   - 레벨: DEBUG(상세) / INFO(정상완료) / WARNING(주의·재시도) / ERROR(실패)
LOG_LEVEL = env("DJANGO_LOG_LEVEL", default="INFO")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "diconai": {
            "format": "{asctime} {levelname:<7} {name}: {message}",
            "datefmt": "%Y-%m-%d %H:%M:%S",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "diconai",
        },
        # AppLog 영속화 — Phase 2-d.
        # ERROR 이상만 캡처 (level=ERROR). 동기 INSTALL — 부하 측정 후 Phase 4에서 비동기 검토.
        # 재귀 가드는 핸들러 내부 thread-local 플래그로 처리.
        "applog_db": {
            "class": "apps.operations.logging.db_handler.DBLogHandler",
            "level": "ERROR",
            "formatter": "diconai",
        },
    },
    "root": {
        "handlers": ["console", "applog_db"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        "django.request": {  # 4xx/5xx 응답 시 Django가 traceback을 남김
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}

# ── Redis ─────────────────────────────────────────────────────
# 로컬 개발: Redis 설치 후 기본 포트(6379)로 실행하면 별도 설정 없이 동작.
# Windows: https://github.com/microsoftarchive/redis/releases
# Mac:     brew install redis && brew services start redis
# Linux:   sudo apt install redis-server && sudo service redis start
# .env에 REDIS_URL=redis://localhost:6379/0 추가 필요.
REDIS_URL = env("REDIS_URL", default="redis://localhost:6379/0")

# ── Celery ────────────────────────────────────────────────────
# Celery worker 실행: celery -A config worker -l info
# (DRF 서버와 별도 터미널에서 실행해야 함)
CELERY_BROKER_URL = REDIS_URL  # 태스크 전달 채널 (Redis)
CELERY_RESULT_BACKEND = REDIS_URL  # 태스크 결과 저장 (Redis)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True

# ── Cache (Redis) ─────────────────────────────────────────────
# 가스 알람 상태(normal/warning/danger)와 WARNING 타이머 task ID를 저장.
# Redis가 동일하게 사용되므로 추가 인프라 없이 동작.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_URL,
    }
}
