# Generated by Django 6.0.4 on 2026-05-13 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MLModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        help_text="동일 sensor_type 안에서 1부터 순차 증가",
                        verbose_name="모델 버전",
                    ),
                ),
                (
                    "sensor_type",
                    models.CharField(
                        choices=[("power", "전력"), ("gas", "가스")],
                        max_length=10,
                        verbose_name="센서 종류",
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[("isolation_forest", "Isolation Forest")],
                        default="isolation_forest",
                        max_length=30,
                        verbose_name="모델 타입",
                    ),
                ),
                (
                    "trained_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="학습 완료 시각"
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="settings.ML_MODELS_DIR 기준 상대 경로",
                        max_length=255,
                        verbose_name=".pkl 파일 경로",
                    ),
                ),
                (
                    "training_data_range_from",
                    models.DateTimeField(verbose_name="학습 데이터 시작"),
                ),
                (
                    "training_data_range_to",
                    models.DateTimeField(verbose_name="학습 데이터 끝"),
                ),
                (
                    "training_sample_count",
                    models.PositiveIntegerField(
                        help_text="윈도우 적용 전 raw row 수",
                        verbose_name="학습 샘플 수",
                    ),
                ),
                (
                    "feature_columns",
                    models.JSONField(
                        help_text="학습에 사용된 컬럼 이름 리스트 (추론 시 동일 순서로 입력)",
                        verbose_name="피처 컬럼",
                    ),
                ),
                (
                    "params_json",
                    models.JSONField(
                        help_text="contamination, n_estimators 등",
                        verbose_name="학습 하이퍼파라미터",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="추론에 사용할 모델 1개당 1건만 True (sensor_type 별로)",
                        verbose_name="활성 모델",
                    ),
                ),
            ],
            options={
                "db_table": "ml_model",
                "indexes": [
                    models.Index(
                        fields=["sensor_type", "is_active"], name="idx_ml_model_active"
                    ),
                    models.Index(fields=["-trained_at"], name="idx_ml_model_trained"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sensor_type", "version"),
                        name="uq_ml_model_sensor_version",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MLAnomalyResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_version_snapshot",
                    models.PositiveIntegerField(
                        help_text="MLModel 삭제되더라도 추론 시점 버전 보존",
                        verbose_name="모델 버전 (스냅샷)",
                    ),
                ),
                (
                    "sensor_type",
                    models.CharField(
                        help_text="power / gas — MLModel.SensorType 값 사용",
                        max_length=10,
                        verbose_name="센서 종류",
                    ),
                ),
                (
                    "sensor_identifier",
                    models.CharField(
                        help_text="예: 'power:device_1:ch3:watt' 또는 'gas:co'",
                        max_length=64,
                        verbose_name="센서 식별자",
                    ),
                ),
                ("measured_at", models.DateTimeField(verbose_name="측정 시각")),
                (
                    "evaluated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="추론 실행 시각"
                    ),
                ),
                (
                    "anomaly_score",
                    models.FloatField(
                        help_text="IF decision_function 또는 score_samples 결과 (음수=이상)",
                        verbose_name="이상도 점수",
                    ),
                ),
                (
                    "prediction",
                    models.CharField(
                        choices=[("normal", "정상"), ("anomaly", "이상")],
                        max_length=10,
                        verbose_name="이상 여부",
                    ),
                ),
                (
                    "risk_classified",
                    models.CharField(
                        choices=[
                            ("normal", "정상"),
                            ("caution", "주의"),
                            ("predict_warn", "예측경고"),
                            ("danger", "위험"),
                        ],
                        default="normal",
                        help_text="STEP D 의 결합 매트릭스로 임계치 평가와 결합한 4단계 분류",
                        max_length=20,
                        verbose_name="결합 위험도",
                    ),
                ),
                (
                    "feature_snapshot_json",
                    models.JSONField(
                        help_text="추론 시 사용된 피처 값 (디버깅·재현용)",
                        verbose_name="입력 피처 스냅샷",
                    ),
                ),
                (
                    "ml_model",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anomaly_results",
                        to="ml.mlmodel",
                        verbose_name="추론 모델",
                    ),
                ),
            ],
            options={
                "db_table": "ml_anomaly_result",
                "indexes": [
                    models.Index(
                        fields=["sensor_identifier", "-measured_at"],
                        name="idx_ml_res_sensor_time",
                    ),
                    models.Index(
                        fields=["prediction", "-measured_at"],
                        name="idx_ml_res_pred_time",
                    ),
                    models.Index(fields=["-evaluated_at"], name="idx_ml_res_eval"),
                ],
            },
        ),
    ]
