# Generated by Django 6.0.4 on 2026-05-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0002_algorithm_sensor_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlanomalyresult',
            name='risk_classified',
            field=models.CharField(choices=[('normal', '정상'), ('caution', '주의'), ('predict_warn', '예측경고'), ('warning', '경고'), ('danger', '위험')], default='normal', help_text='STEP D 의 결합 매트릭스로 임계치 평가와 결합한 4단계 분류', max_length=20, verbose_name='결합 위험도'),
        ),
    ]
