# Generated by Django 6.0.4 on 2026-06-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0003_alter_mlanomalyresult_risk_classified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlanomalyresult',
            name='risk_classified',
            field=models.CharField(choices=[('normal', '정상'), ('caution', '주의'), ('predict_warn', '예측경고'), ('warning', '경고'), ('danger', '위험')], default='normal', help_text='결합 매트릭스로 임계치 평가와 AI 신호를 합친 분류', max_length=20, verbose_name='결합 위험도'),
        ),
    ]
