# Generated by Django 6.0.4 on 2026-04-21 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("facilities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GasData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("co", models.FloatField(null=True, verbose_name="일산화탄소 (ppm)")),
                ("h2s", models.FloatField(null=True, verbose_name="황화수소 (ppm)")),
                ("co2", models.FloatField(null=True, verbose_name="이산화탄소 (ppm)")),
                ("o2", models.FloatField(null=True, verbose_name="산소 (%)")),
                ("no2", models.FloatField(null=True, verbose_name="이산화질소 (ppm)")),
                ("so2", models.FloatField(null=True, verbose_name="이산화황 (ppm)")),
                ("o3", models.FloatField(null=True, verbose_name="오존 (ppm)")),
                ("nh3", models.FloatField(null=True, verbose_name="암모니아 (ppm)")),
                (
                    "voc",
                    models.FloatField(null=True, verbose_name="휘발성유기화합물 (ppm)"),
                ),
                (
                    "co_risk",
                    models.CharField(
                        choices=[
                            ("normal", "정상"),
                            ("warning", "주의"),
                            ("danger", "위험"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="CO 위험도",
                    ),
                ),
                (
                    "h2s_risk",
                    models.CharField(
                        choices=[
                            ("normal", "정상"),
                            ("warning", "주의"),
                            ("danger", "위험"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="H2S 위험도",
                    ),
                ),
                (
                    "co2_risk",
                    models.CharField(
                        choices=[
                            ("normal", "정상"),
                            ("warning", "주의"),
                            ("danger", "위험"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="CO2 위험도",
                    ),
                ),
                (
                    "o2_risk",
                    models.CharField(
                        choices=[
                            ("normal", "정상"),
                            ("warning", "주의"),
                            ("danger", "위험"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="O2 위험도",
                    ),
                ),
                (
                    "no2_risk",
                    models.CharField(
                        choices=[
                            ("normal", "정상"),
                            ("warning", "주의"),
                            ("danger", "위험"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="NO2 위험도",
                    ),
                ),
                (
                    "so2_risk",
                    models.CharField(
                        choices=[
                            ("normal", "정상"),
                            ("warning", "주의"),
                            ("danger", "위험"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="SO2 위험도",
                    ),
                ),
                (
                    "o3_risk",
                    models.CharField(
                        choices=[
                            ("normal", "정상"),
                            ("warning", "주의"),
                            ("danger", "위험"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="O3 위험도",
                    ),
                ),
                (
                    "nh3_risk",
                    models.CharField(
                        choices=[
                            ("normal", "정상"),
                            ("warning", "주의"),
                            ("danger", "위험"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="NH3 위험도",
                    ),
                ),
                (
                    "voc_risk",
                    models.CharField(
                        choices=[
                            ("normal", "정상"),
                            ("warning", "주의"),
                            ("danger", "위험"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="VOC 위험도",
                    ),
                ),
                (
                    "max_risk_level",
                    models.CharField(
                        choices=[
                            ("normal", "정상"),
                            ("warning", "주의"),
                            ("danger", "위험"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="최고 위험도",
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(
                        blank=True, null=True, verbose_name="원본 수신 페이로드"
                    ),
                ),
                ("measured_at", models.DateTimeField(verbose_name="측정 시각")),
                (
                    "received_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="수신 시각"),
                ),
                (
                    "gas_sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gas_data",
                        to="facilities.gassensor",
                    ),
                ),
            ],
            options={
                "db_table": "gas_data",
            },
        ),
        migrations.CreateModel(
            name="GasDataError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_gas",
                    models.CharField(
                        choices=[
                            ("co", "일산화탄소"),
                            ("h2s", "황화수소"),
                            ("co2", "이산화탄소"),
                            ("o2", "산소"),
                            ("no2", "이산화질소"),
                            ("so2", "이산화황"),
                            ("o3", "오존"),
                            ("nh3", "암모니아"),
                            ("voc", "휘발성유기화합물"),
                        ],
                        max_length=20,
                        verbose_name="대상 가스",
                    ),
                ),
                (
                    "error_type",
                    models.CharField(
                        choices=[
                            ("MISSING", "데이터 누락(결측)"),
                            ("SENSOR_FAULT", "센서 고장"),
                        ],
                        default="MISSING",
                        max_length=20,
                        verbose_name="에러 유형",
                    ),
                ),
                (
                    "gas_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errors",
                        to="monitoring.gasdata",
                    ),
                ),
            ],
            options={
                "db_table": "gas_data_error",
            },
        ),
        migrations.CreateModel(
            name="PowerData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.PositiveSmallIntegerField(verbose_name="채널 번호 (1~16)"),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("current", "전류 (A)"),
                            ("voltage", "전압 (V)"),
                            ("watt", "전력 (W)"),
                        ],
                        max_length=20,
                        verbose_name="측정 종류",
                    ),
                ),
                ("value", models.FloatField(verbose_name="측정값")),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("normal", "정상"),
                            ("warning", "주의"),
                            ("danger", "위험"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("measured_at", models.DateTimeField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "power_device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="power_data",
                        to="facilities.powerdevice",
                    ),
                ),
            ],
            options={
                "db_table": "power_data",
            },
        ),
        migrations.CreateModel(
            name="PowerEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot", models.JSONField(verbose_name="16채널 상태 스냅샷")),
                (
                    "changed_channels",
                    models.JSONField(
                        blank=True, null=True, verbose_name="변경된 채널 번호 리스트"
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("manual", "수동 조작"),
                            ("alarm_auto", "알람 자동 차단"),
                            ("recovery_auto", "자동 복구"),
                            ("power_cut", "전원 차단"),
                            ("unknown", "원인 불명"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="이벤트 원인",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "power_device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="power_events",
                        to="facilities.powerdevice",
                    ),
                ),
            ],
            options={
                "db_table": "power_event",
            },
        ),
        migrations.AddIndex(
            model_name="gasdata",
            index=models.Index(
                fields=["gas_sensor", "-measured_at"], name="idx_gas_data_sensor_time"
            ),
        ),
        migrations.AddIndex(
            model_name="gasdata",
            index=models.Index(fields=["-measured_at"], name="idx_gas_data_time"),
        ),
        migrations.AddIndex(
            model_name="gasdata",
            index=models.Index(
                fields=["max_risk_level", "-measured_at"], name="idx_gas_data_risk_time"
            ),
        ),
        migrations.AddIndex(
            model_name="gasdataerror",
            index=models.Index(
                fields=["target_gas", "error_type"], name="idx_gas_error_target_type"
            ),
        ),
        migrations.AddIndex(
            model_name="powerdata",
            index=models.Index(
                fields=["power_device", "channel", "-measured_at"],
                name="idx_pwr_device_ch_time",
            ),
        ),
        migrations.AddIndex(
            model_name="powerdata",
            index=models.Index(
                fields=["power_device", "channel", "data_type", "-measured_at"],
                name="idx_pwr_device_ch_type_time",
            ),
        ),
        migrations.AddIndex(
            model_name="powerdata",
            index=models.Index(fields=["-measured_at"], name="idx_pwr_time"),
        ),
        migrations.AddIndex(
            model_name="powerdata",
            index=models.Index(
                fields=["risk_level", "-measured_at"], name="idx_pwr_risk_time"
            ),
        ),
        migrations.AddConstraint(
            model_name="powerdata",
            constraint=models.UniqueConstraint(
                fields=("power_device", "channel", "data_type", "measured_at"),
                name="uq_power_data_device_channel_type_time",
            ),
        ),
        migrations.AddIndex(
            model_name="powerevent",
            index=models.Index(
                fields=["power_device", "-created_at"],
                name="idx_power_event_device_time",
            ),
        ),
    ]
