# Generated by Django 6.0.4 on 2026-04-20 05:07

import apps.monitoring.models.power_event
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("facilities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GasData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "measurements",
                    models.JSONField(
                        default=dict, verbose_name="가스별 측정값 및 위험도"
                    ),
                ),
                (
                    "max_risk_level",
                    models.CharField(
                        choices=[
                            ("normal", "정상"),
                            ("warning", "주의"),
                            ("danger", "위험"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="최고 위험도",
                    ),
                ),
                ("measured_at", models.DateTimeField(verbose_name="측정 시각")),
                (
                    "received_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="수신 시각"),
                ),
                (
                    "gas_sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gas_data",
                        to="facilities.gassensor",
                    ),
                ),
            ],
            options={
                "db_table": "gas_data",
            },
        ),
        migrations.CreateModel(
            name="GasDataError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_gas",
                    models.CharField(
                        help_text="오류가 발생한 가스 (예: 'co', 'o2', 'system')",
                        max_length=20,
                        verbose_name="대상 가스",
                    ),
                ),
                (
                    "error_type",
                    models.CharField(
                        choices=[
                            ("MISSING", "데이터 누락(결측)"),
                            ("SENSOR_FAULT", "센서 고장"),
                        ],
                        default="MISSING",
                        max_length=20,
                        verbose_name="에러 유형",
                    ),
                ),
                (
                    "gas_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errors",
                        to="monitoring.gasdata",
                    ),
                ),
            ],
            options={
                "db_table": "gas_data_error",
            },
        ),
        migrations.CreateModel(
            name="PowerData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.PositiveSmallIntegerField(verbose_name="채널 번호 (1~16)"),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("current", "전류 (A)"),
                            ("voltage", "전압 (V)"),
                            ("watt", "전력 (W)"),
                        ],
                        max_length=20,
                        verbose_name="측정 종류",
                    ),
                ),
                ("value", models.FloatField(verbose_name="측정값")),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("normal", "정상"),
                            ("warning", "주의"),
                            ("danger", "위험"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("measured_at", models.DateTimeField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "power_device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="power_data",
                        to="facilities.powerdevice",
                    ),
                ),
            ],
            options={
                "db_table": "power_data",
            },
        ),
        migrations.CreateModel(
            name="PowerEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "snapshot",
                    models.JSONField(
                        validators=[
                            apps.monitoring.models.power_event.validate_snapshot
                        ],
                        verbose_name="16채널 상태 스냅샷",
                    ),
                ),
                (
                    "changed_channels",
                    models.JSONField(
                        blank=True, default=list, verbose_name="변경된 채널 번호 리스트"
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("manual_admin", "관리자 수동 조작"),
                            ("auto_alarm", "알람 자동 차단"),
                            ("auto_recovery", "자동 복구"),
                            ("power_outage", "전원 차단"),
                            ("unknown", "원인 불명"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="이벤트 원인",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "power_device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="power_events",
                        to="facilities.powerdevice",
                    ),
                ),
            ],
            options={
                "db_table": "power_event",
            },
        ),
        migrations.AddIndex(
            model_name="gasdata",
            index=models.Index(
                fields=["gas_sensor", "-measured_at"], name="idx_gas_data_sensor_time"
            ),
        ),
        migrations.AddIndex(
            model_name="gasdata",
            index=models.Index(fields=["-measured_at"], name="idx_gas_data_time"),
        ),
        migrations.AddIndex(
            model_name="gasdata",
            index=models.Index(
                fields=["max_risk_level", "-measured_at"], name="idx_gas_data_risk_time"
            ),
        ),
        migrations.AddIndex(
            model_name="gasdataerror",
            index=models.Index(
                fields=["target_gas", "error_type"], name="idx_gas_error_target_type"
            ),
        ),
        migrations.AddIndex(
            model_name="powerdata",
            index=models.Index(
                fields=["power_device", "channel", "-measured_at"],
                name="idx_pwr_device_ch_time",
            ),
        ),
        migrations.AddIndex(
            model_name="powerdata",
            index=models.Index(fields=["-measured_at"], name="idx_pwr_time"),
        ),
        migrations.AddIndex(
            model_name="powerdata",
            index=models.Index(
                fields=["risk_level", "-measured_at"], name="idx_pwr_risk_time"
            ),
        ),
        migrations.AddConstraint(
            model_name="powerdata",
            constraint=models.UniqueConstraint(
                fields=("power_device", "channel", "data_type", "measured_at"),
                name="uq_power_data_device_channel_type_time",
            ),
        ),
        migrations.AddIndex(
            model_name="powerevent",
            index=models.Index(
                fields=["power_device", "-created_at"], name="idx_pwr_event_device_time"
            ),
        ),
        migrations.AddIndex(
            model_name="powerevent",
            index=models.Index(
                fields=["trigger", "-created_at"], name="idx_pwr_event_trigger_time"
            ),
        ),
    ]
