# Generated by Django 6.0.4 on 2026-05-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facilities", "0018_seed_power_facility_default"),
        ("monitoring", "0006_powerdata_is_anomaly_anomaly_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="gasdata",
            name="anomaly_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("co_leak", "일산화탄소 누출"),
                    ("h2s_leak", "황화수소 누출"),
                    ("fire", "화재/폭발 전조"),
                    ("chemical_spill", "유해화학물 다중 누출"),
                ],
                help_text="더미 시뮬레이터 시나리오 라벨 — IF 학습 평가용",
                max_length=20,
                null=True,
                verbose_name="이상 시나리오",
            ),
        ),
        migrations.AddField(
            model_name="gasdata",
            name="is_anomaly",
            field=models.BooleanField(
                default=False,
                help_text="더미 시뮬레이터/운영자 라벨링용",
                verbose_name="이상 라벨",
            ),
        ),
        migrations.AddIndex(
            model_name="gasdata",
            index=models.Index(
                fields=["is_anomaly", "-measured_at"], name="idx_gas_anomaly_time"
            ),
        ),
    ]
