# Generated by Django 6.0.4 on 2026-05-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_gasdata_is_anomaly_anomaly_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerdata',
            name='anomaly_type',
            field=models.CharField(blank=True, choices=[('overload', '과부하'), ('voltage_drop', '저전압'), ('spike', '스파이크'), ('phase_loss', '결상'), ('degradation', '열화'), ('night_abnormal', '야간 가동'), ('motor_stuck', '모터 정지')], help_text='더미 시뮬레이터 시나리오 라벨 — IF 학습 평가용', max_length=20, null=True, verbose_name='이상 시나리오'),
        ),
    ]
