# Generated by Django 6.0.4 on 2026-06-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_alter_powerdata_anomaly_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasdata',
            name='anomaly_type',
            field=models.CharField(blank=True, choices=[('co_leak', '일산화탄소 누출'), ('h2s_leak', '황화수소 누출'), ('fire', '화재/폭발 전조'), ('chemical_spill', '유해화학물 다중 누출'), ('o2_depletion', '산소 결핍'), ('sensor_fault', '센서 오작동')], help_text='더미 시뮬레이터 시나리오 라벨 — IF 학습 평가용', max_length=20, null=True, verbose_name='이상 시나리오'),
        ),
    ]
