# Generated by Django 6.0.4 on 2026-04-20 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("facilities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SafetyCheckItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="항목 제목")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="상세 설명"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="표시 순서"
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=True, verbose_name="필수 여부"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safety_check_items",
                        to="facilities.facility",
                    ),
                ),
            ],
            options={
                "db_table": "safety_check_item",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SafetyStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "check_item_title",
                    models.CharField(
                        help_text="항목이 삭제돼도 당시 제목 보존",
                        max_length=200,
                        verbose_name="체크 당시 항목 제목 (스냅샷)",
                    ),
                ),
                ("is_checked", models.BooleanField(default=False)),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "note",
                    models.TextField(
                        blank=True, default="", verbose_name="작업자 메모"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "check_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="statuses",
                        to="safety.safetycheckitem",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="safety_statuses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "safety_status",
            },
        ),
        migrations.AddIndex(
            model_name="safetycheckitem",
            index=models.Index(
                fields=["facility", "is_active", "order"],
                name="idx_scitem_fac_active_order",
            ),
        ),
        migrations.AddIndex(
            model_name="safetystatus",
            index=models.Index(
                fields=["worker", "-checked_at"], name="idx_safety_worker_time"
            ),
        ),
        migrations.AddIndex(
            model_name="safetystatus",
            index=models.Index(
                fields=["check_item", "is_checked"], name="idx_safety_item_checked"
            ),
        ),
        migrations.AddConstraint(
            model_name="safetystatus",
            constraint=models.UniqueConstraint(
                fields=("worker", "check_item"), name="uq_safety_worker_item"
            ),
        ),
    ]
