# Generated by Django 6.0.4 on 2026-05-08 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facilities", "0010_thresholdgroup_threshold"),
        ("safety", "0002_safetycheckitem_updated_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SafetyCheckSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="최근 수정일"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="섹션 이름")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="섹션 설명"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="섹션 순서"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="safety_check_sections",
                        to="facilities.facility",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최근 수정자",
                    ),
                ),
            ],
            options={
                "db_table": "safety_check_section",
                "ordering": ["facility", "order"],
            },
        ),
        migrations.AddField(
            model_name="safetycheckitem",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="safety.safetychecksection",
            ),
        ),
        migrations.AddIndex(
            model_name="safetychecksection",
            index=models.Index(
                fields=["facility", "is_active", "order"],
                name="idx_section_fac_active_order",
            ),
        ),
    ]
