# Generated by Django 6.0.4 on 2026-05-08 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facilities", "0010_thresholdgroup_threshold"),
        ("safety", "0005_safetycheckitem_section_not_null"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SafetyChecklistRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="최근 수정일"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        help_text="공장별 1, 2, 3, ... 자동 부여 (서비스 레이어에서 max+1)",
                        verbose_name="버전 번호",
                    ),
                ),
                (
                    "revision_data",
                    models.JSONField(
                        default=dict,
                        help_text="발행 시점 Section 트리 + Item 메타",
                        verbose_name="개정 스냅샷",
                    ),
                ),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="facility별 1개만 True (부분 UniqueConstraint)",
                        verbose_name="활성 개정",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checklist_revisions",
                        to="facilities.facility",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최근 수정자",
                    ),
                ),
            ],
            options={
                "db_table": "safety_checklist_revision",
                "ordering": ["facility", "-version"],
            },
        ),
        migrations.CreateModel(
            name="SafetyCheckSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="최근 수정일"),
                ),
                ("date", models.DateField(verbose_name="작업일")),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False, verbose_name="완료 여부 (모든 필수 항목 체크)"
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="safety.safetychecklistrevision",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최근 수정자",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="safety_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "safety_check_session",
                "ordering": ["-date"],
            },
        ),
        migrations.AddField(
            model_name="safetystatus",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="statuses",
                to="safety.safetychecksession",
            ),
        ),
        migrations.AddIndex(
            model_name="safetychecklistrevision",
            index=models.Index(
                fields=["facility", "is_active"], name="idx_revision_fac_active"
            ),
        ),
        migrations.AddConstraint(
            model_name="safetychecklistrevision",
            constraint=models.UniqueConstraint(
                fields=("facility", "version"), name="uq_revision_facility_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="safetychecklistrevision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("facility",),
                name="uq_revision_facility_active",
            ),
        ),
        migrations.AddIndex(
            model_name="safetychecksession",
            index=models.Index(
                fields=["worker", "-date"], name="idx_session_worker_date"
            ),
        ),
        migrations.AddIndex(
            model_name="safetychecksession",
            index=models.Index(
                fields=["revision", "-date"], name="idx_session_revision_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="safetychecksession",
            constraint=models.UniqueConstraint(
                fields=("worker", "date", "revision"),
                name="uq_session_worker_date_revision",
            ),
        ),
    ]
