# Generated by Django 6.0.4 on 2026-04-14 18:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loginlog",
            name="ip_address",
        ),
    ]
