# Generated by Django 6.0.4 on 2026-04-16 00:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_loginlog_ip_address'),
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='loginlog',
            name='action',
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='sensors.facility'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', '관리자'), ('worker', '작업자')], default='worker', max_length=20),
        ),
        migrations.AddField(
            model_name='loginlog',
            name='ip_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loginlog',
            name='is_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='custom_user',
        ),
        migrations.AlterModelTable(
            name='loginlog',
            table='login_log',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
