# Generated by Django 6.0.4 on 2026-04-21 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_login",
                    models.BooleanField(
                        default=False, verbose_name="로그인 여부 (False=로그아웃)"
                    ),
                ),
                (
                    "login_result",
                    models.CharField(
                        choices=[
                            ("success", "성공"),
                            ("failed_password", "비밀번호 오류"),
                            ("failed_locked", "계정 잠금"),
                            ("failed_inactive", "비활성 계정"),
                            ("logout", "로그아웃"),
                        ],
                        max_length=20,
                        verbose_name="로그인 결과",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="접속 IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="User-Agent",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=40,
                        verbose_name="세션 키 (로그인-로그아웃 쌍 매칭용)",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="login_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "db_table": "login_log",
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"], name="idx_login_user_time"
                    ),
                    models.Index(
                        fields=["ip_address", "-timestamp"], name="idx_login_ip_time"
                    ),
                    models.Index(
                        fields=["login_result", "-timestamp"],
                        name="idx_login_result_time",
                    ),
                    models.Index(fields=["-timestamp"], name="idx_login_time"),
                ],
            },
        ),
    ]
