# Generated by Django 6.0.4 on 2026-04-27 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_loginlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="부서명"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="부서 코드"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="사용 여부"),
                ),
            ],
            options={
                "verbose_name": "부서",
                "db_table": "department",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, unique=True, verbose_name="직급명"),
                ),
                ("level", models.PositiveSmallIntegerField(verbose_name="정렬 레벨")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("office", "사무직"),
                            ("field", "현장직"),
                            ("executive", "임원진"),
                        ],
                        max_length=20,
                        verbose_name="분류",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="사용 여부"),
                ),
            ],
            options={
                "verbose_name": "직급",
                "db_table": "position",
                "ordering": ["level"],
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="실명"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("super_admin", "슈퍼관리자"),
                    ("facility_admin", "관리자"),
                    ("worker", "일반사용자"),
                    ("viewer", "열람자"),
                ],
                default="worker",
                max_length=20,
                verbose_name="사용자 유형",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="accounts.department",
                verbose_name="소속 부서",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="accounts.position",
                verbose_name="직급",
            ),
        ),
    ]
