# Generated by Django 6.0.4 on 2026-04-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_customuser_options_remove_loginlog_action_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("superadmin", "슈퍼관리자"),
                    ("admin", "관리자"),
                    ("worker", "작업자"),
                ],
                default="worker",
                max_length=20,
            ),
        ),
    ]
