# Generated by Django 6.0.4 on 2026-05-08 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_gas_sensor_fields_inspection"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="최근 수정일"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="역할 코드"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="역할 명")),
                (
                    "base_user_type",
                    models.CharField(
                        choices=[
                            ("super_admin", "슈퍼관리자"),
                            ("facility_admin", "관리자"),
                            ("worker", "일반사용자"),
                            ("viewer", "열람자"),
                        ],
                        max_length=20,
                        verbose_name="기반 사용자 유형",
                    ),
                ),
                (
                    "platform_type",
                    models.CharField(
                        choices=[("web", "웹 어드민"), ("app", "모바일 앱")],
                        default="web",
                        max_length=10,
                        verbose_name="플랫폼",
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최근 수정자",
                    ),
                ),
            ],
            options={
                "db_table": "role_profile",
                "ordering": ["code"],
            },
        ),
    ]
