# Generated by Django 6.0.4 on 2026-06-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_seed_role_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='discord_id',
            field=models.CharField(blank=True, default='', help_text='Discord 개인 멘션용 숫자 ID. 비어 있으면 멘션 대상 제외.', max_length=32, verbose_name='Discord 사용자 ID'),
        ),
    ]
