# Generated by Django 6.0.4 on 2026-05-08 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0009_roleprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="최근 수정일"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="메뉴 코드"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="표시 명")),
                (
                    "menu_type",
                    models.CharField(
                        choices=[("snb", "사이드바"), ("admin", "어드민")],
                        default="snb",
                        max_length=20,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("icon", models.CharField(blank=True, default="", max_length=50)),
                ("url_path", models.CharField(blank=True, default="", max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="dashboard.menu",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최근 수정자",
                    ),
                ),
            ],
            options={
                "db_table": "menu",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="RoleMenuVisibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="최근 수정일"),
                ),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_visibilities",
                        to="dashboard.menu",
                    ),
                ),
                (
                    "role_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_visibilities",
                        to="accounts.roleprofile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최근 수정자",
                    ),
                ),
            ],
            options={
                "db_table": "role_menu_visibility",
            },
        ),
        migrations.AddIndex(
            model_name="menu",
            index=models.Index(
                fields=["menu_type", "sort_order"], name="menu_menu_ty_44c85a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="menu",
            index=models.Index(
                fields=["parent", "sort_order"], name="menu_parent__231e2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rolemenuvisibility",
            index=models.Index(
                fields=["role_profile", "is_visible"],
                name="role_menu_v_role_pr_77ba31_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="rolemenuvisibility",
            constraint=models.UniqueConstraint(
                fields=("role_profile", "menu"), name="uq_rolemenu"
            ),
        ),
    ]
