# Generated by Django 6.0.4 on 2026-05-08 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("facilities", "0010_thresholdgroup_threshold"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VRTrainingContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="최근 수정일"),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("gas_sensor", "가스 센서"), ("general", "일반")],
                        max_length=20,
                        verbose_name="적용 대상",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("content_url", models.URLField(max_length=500)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "target_facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL이면 전사 콘텐츠",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vr_contents",
                        to="facilities.facility",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최근 수정자",
                    ),
                ),
            ],
            options={
                "db_table": "vr_training_content",
            },
        ),
        migrations.CreateModel(
            name="VRTrainingRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="최근 수정일"),
                ),
                (
                    "previous_url",
                    models.URLField(max_length=500, verbose_name="이전 URL"),
                ),
                (
                    "previous_name",
                    models.CharField(max_length=200, verbose_name="이전 명"),
                ),
                ("replaced_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="training.vrtrainingcontent",
                    ),
                ),
                (
                    "replaced_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vr_revisions_replaced",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최근 수정자",
                    ),
                ),
            ],
            options={
                "db_table": "vr_training_revision",
            },
        ),
        migrations.AddIndex(
            model_name="vrtrainingcontent",
            index=models.Index(
                fields=["target_type", "target_facility", "is_active"],
                name="idx_vr_target_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="vrtrainingcontent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("target_type", "target_facility"),
                name="uq_vr_active_target",
            ),
        ),
        migrations.AddIndex(
            model_name="vrtrainingrevision",
            index=models.Index(
                fields=["content", "-replaced_at"], name="idx_vrrev_content_time"
            ),
        ),
    ]
